/** @vercel/include */ require("xml2js");

import { NextResponse } from "next/server";

// ========== STYLE MAPPING: NetEase wiki style -> our genre categories ==========
function mapWikiStyle(wikiStyle: string): string | null {
  if (!wikiStyle) return null;
  const styleMap: Record<string, string> = {
    "流行-华语流行": "华语流行",
    "流行-粤语流行": "粤语流行",
    "流行-欧美流行": "欧美流行",
    "流行-KPop": "K-Pop",
    "流行-日本流行": "J-Pop",
    "流行-流行舞曲": "流行舞曲",
    "流行-City Pop": "City Pop",
    "嘻哈说唱": "嘻哈/说唱",
    "嘻哈说唱-中文说唱": "嘻哈/说唱",
    "嘻哈说唱-流行说唱": "流行说唱",
    "嘻哈说唱-旋律说唱": "旋律说唱",
    "嘻哈说唱-陷阱说唱": "陷阱说唱",
    "嘻哈说唱-钻头说唱": "钻头说唱",
    "嘻哈说唱-爵士嘻哈": "爵士嘻哈",
    "嘻哈说唱-硬核说唱": "硬核说唱",
    "嘻哈说唱-情绪说唱": "情绪说唱",
    "嘻哈说唱-意识说唱": "意识说唱",
    "嘻哈说唱-匪帮说唱": "匪帮说唱",
    "嘻哈说唱-Boom Bap": "Boom Bap",
    "嘻哈说唱-车库嘻哈": "车库嘻哈",
    "摇滚": "摇滚",
    "摇滚-华语摇滚": "华语摇滚",
    "摇滚-流行摇滚": "流行摇滚",
    "摇滚-独立摇滚": "独立摇滚",
    "摇滚-另类摇滚": "另类摇滚",
    "摇滚-硬摇滚": "硬摇滚",
    "摇滚-金属": "金属",
    "摇滚-朋克": "朋克",
    "摇滚-民谣摇滚": "民谣摇滚",
    "摇滚-后摇": "后摇",
    "摇滚-迷幻摇滚": "迷幻摇滚",
    "摇滚-情绪摇滚": "情绪摇滚",
    "摇滚-数字摇滚": "数字摇滚",
    "摇滚-英伦摇滚": "英伦摇滚",
    "民谣": "民谣",
    "民谣-华语民谣": "华语民谣",
    "民谣-当代民谣": "当代民谣",
    "民谣-独立民谣": "独立民谣",
    "民谣-新民谣": "新民谣",
    "民谣-美式民谣": "美式民谣",
    "电子": "电子",
    "电子-浩室": "浩室",
    "电子-迷幻舞曲": "迷幻舞曲",
    "电子-电子舞曲": "电子舞曲",
    "电子-氛围音乐": "氛围音乐",
    "电子-回响贝斯": "回响贝斯",
    "电子-碎拍": "碎拍",
    "电子-合成器": "合成器",
    "电子-弛放": "弛放",
    "R&B/Soul": "R&B",
    "R&B/Soul-当代节奏布鲁斯": "R&B",
    "R&B/Soul-灵魂乐": "灵魂乐",
    "R&B/Soul-放克": "放克",
    "R&B/Soul-新灵魂乐": "新灵魂乐",
    "R&B/Soul-白人灵魂乐": "白人灵魂乐",
    "R&B/Soul-无伴奏合唱": "无伴奏合唱",
    "古风": "古风/中国风",
    "古风-中国风": "古风/中国风",
    "古风-原创古风": "古风/中国风",
    "ACG": "二次元/ACG",
    "ACG-动漫": "二次元/ACG",
    "ACG-游戏": "二次元/ACG",
    "ACG-VOCALOID": "二次元/ACG",
    "ACG-声优": "二次元/ACG",
    "爵士": "爵士",
    "爵士-当代爵士": "爵士",
    "爵士- Smooth Jazz": "爵士",
    "爵士-波萨诺瓦": "波萨诺瓦",
    "爵士-自由爵士": "自由爵士",
    "爵士-冷爵士": "冷爵士",
    "古典": "古典",
    "古典-交响乐": "交响乐",
    "古典-协奏曲": "协奏曲",
    "古典-室内乐": "室内乐",
    "古典-歌剧": "歌剧",
    "古典-钢琴曲": "钢琴曲",
    "古典-管弦乐": "管弦乐",
    "轻音乐": "轻音乐",
    "轻音乐-钢琴轻音乐": "轻音乐",
    "轻音乐-抒情轻音乐": "轻音乐",
    "乡村": "乡村",
    "乡村-当代乡村": "乡村",
    "乡村-流行乡村": "乡村",
    "乡村-乡村摇滚": "乡村摇滚",
    "蓝调": "蓝调",
    "蓝调-当代蓝调": "蓝调",
    "蓝调-钢琴蓝调": "蓝调",
    "蓝调-城市布鲁斯": "蓝调",
    "放克": "放克",
    "放克-深度放克": "放克",
    "雷鬼": "雷鬼",
    "雷鬼-斯卡": "斯卡",
    "雷鬼-舞场雷鬼": "舞场雷鬼",
    "拉丁音乐": "拉丁",
    "拉丁音乐-拉丁流行": "拉丁流行",
    "另类/独立": "独立",
    "另类/独立-独立流行": "独立流行",
    "另类/独立-另类流行": "另类流行",
    "世界音乐": "世界音乐",
  };

  if (styleMap[wikiStyle]) return styleMap[wikiStyle];

  const parts = wikiStyle.split("-");
  if (parts.length > 0) {
    const mainCat = parts[0];
    if (styleMap[mainCat]) {
      return styleMap[mainCat];
    }
  }
  return null;
}

// ========== ARTIST GENRE DATABASE ==========
const ARTIST_GENRES: Record<string, string[]> = {
  "Stevie Wonder": ["R&B", "灵魂乐"],
  "Marvin Gaye": ["R&B", "灵魂乐"],
  "Lionel Richie": ["R&B", "流行"],
  "Michael Jackson": ["流行", "R&B", "放克"],
  "Jackson 5": ["R&B", "灵魂乐", "放克"],
  "The Temptations": ["R&B", "灵魂乐"],
  "Smokey Robinson": ["R&B", "灵魂乐"],
  "Four Tops": ["R&B", "灵魂乐"],
  "Stacy Lattisaw": ["R&B", "灵魂乐"],
  "Dazz Band": ["放克", "R&B"],
  "Babyface": ["R&B"],
  "Boyz II Men": ["R&B"],
  "Toni Braxton": ["R&B"],
  "Mariah Carey": ["R&B", "流行"],
  "Whitney Houston": ["R&B", "流行"],
  "Beyonce": ["R&B", "流行"],
  "Beyoncé": ["R&B", "流行"],
  "Usher": ["R&B", "流行"],
  "Alicia Keys": ["R&B", "灵魂乐"],
  "John Legend": ["R&B", "灵魂乐"],
  "Frank Ocean": ["R&B", "灵魂乐"],
  "Miguel": ["R&B"],
  "SZA": ["R&B"],
  "Erykah Badu": ["R&B", "灵魂乐"],
  "Lauryn Hill": ["R&B", "嘻哈/说唱"],
  "Aaliyah": ["R&B"],
  "TLC": ["R&B", "流行"],
  "Craig David": ["R&B"],
  "Sade": ["R&B", "灵魂乐", "爵士"],
  "Anita Baker": ["R&B", "灵魂乐"],
  "Luther Vandross": ["R&B", "灵魂乐"],
  "Al Green": ["R&B", "灵魂乐"],
  "Aretha Franklin": ["R&B", "灵魂乐"],
  "Ray Charles": ["R&B", "灵魂乐", "蓝调"],
  "Otis Redding": ["R&B", "灵魂乐"],
  "Sam Smith": ["R&B", "流行"],
  "The Weeknd": ["R&B", "流行"],
  "Bruno Mars": ["放克", "R&B", "流行"],
  "Summer Walker": ["R&B"],
  "Kendrick Lamar": ["嘻哈/说唱"],
  "Drake": ["嘻哈/说唱", "流行"],
  "Eminem": ["嘻哈/说唱"],
  "Queen": ["摇滚"],
  "Diana Ross": ["R&B", "灵魂乐", "流行"],
  "The Supremes": ["R&B", "灵魂乐", "流行"],
  "Commodores": ["R&B", "放克", "灵魂乐"],
  "DeBarge": ["R&B", "灵魂乐", "放克"],
  "Mary Wells": ["R&B", "灵魂乐"],
  "Bobby King": ["R&B", "灵魂乐"],
  "Angela Cole": ["R&B", "灵魂乐"],
  "Maureen Steele": ["R&B", "灵魂乐"],
  "Etta James": ["蓝调", "灵魂乐"],
  "B.B. King": ["蓝调"],
  "The Beatles": ["摇滚", "流行"],
  "Coldplay": ["流行摇滚", "另类摇滚"],
  "Twins": ["粤语流行"],
  "刘德华": ["华语流行"],
  "张学友": ["华语流行"],
  "陈奕迅": ["华语流行"],
  "周杰伦": ["华语流行"],
  "林俊杰": ["华语流行"],
  "王力宏": ["华语流行", "R&B"],
  "陶喆": ["R&B", "华语流行"],
  "方大同": ["R&B", "华语流行"],
  "五月天": ["华语摇滚"],
  "苏打绿": ["独立流行"],
  "银临": ["古风/中国风"],
  "河图": ["古风/中国风"],
  "音频怪物": ["古风/中国风"],
  "东篱": ["古风/中国风"],
  "小曲儿": ["古风/中国风"],
  "HITA": ["古风/中国风"],
  "董贞": ["古风/中国风"],
  "少司命": ["古风/中国风"],
  "Vava": ["嘻哈/说唱"],
  "Higher Brothers": ["嘻哈/说唱"],
  "Lexie Liu": ["流行说唱"],
  "Jony J": ["嘻哈/说唱"],
  "GAI": ["嘻哈/说唱"],
  "Brant": ["嘻哈/说唱"],
  "PG One": ["嘻哈/说唱"],
  "Kris": ["华语流行"],
  "Tia": ["R&B"],
  "Lala": ["华语流行"],
  "Jolin": ["流行舞曲"],
  "Jay": ["华语流行"],
  "JJ Lin": ["华语流行"],
  "David Tao": ["R&B"],
  "Khalil": ["R&B"],
  "Wang Leehom": ["华语流行"],
  "Yoga Lin": ["独立流行"],
  "LaLa Hsu": ["华语流行"],
  "Hebe": ["华语流行"],
  "Hush": ["独立摇滚"],
  "Miyavi": ["J-Pop"],
  "ONE OK ROCK": ["J-Pop", "摇滚"],
  "RADWIMPS": ["J-Pop", "摇滚"],
  "Yoasobi": ["J-Pop"],
  "Lisa": ["J-Pop"],
  "Ado": ["J-Pop"],
  "Nujabes": ["爵士嘻哈"],
  "FKJ": ["电子"],
  "Tom Misch": ["R&B"],
  "Ice Paper": ["嘻哈/说唱"],
  "蔡徐坤": ["华语流行"],
  "张艺兴": ["流行舞曲", "华语流行"],
  "王嘉尔": ["嘻哈/说唱"],
  "黄子韬": ["流行舞曲"],
  "吴亦凡": ["华语流行"],
  "薛之谦": ["华语流行"],
  "李荣浩": ["华语流行"],
  "邓紫棋": ["华语流行"],
  "周深": ["华语流行"],
  "华晨宇": ["华语流行"],
  "毛不易": ["华语民谣"],
  "梁博": ["华语摇滚"],
  "赵雷": ["华语民谣"],
  "陈粒": ["独立流行"],
  "许嵩": ["华语流行"],
  "汪苏泷": ["华语流行"],
  "徐佳莹": ["华语流行"],
  "王菲": ["华语流行"],
  "那英": ["华语流行"],
  "孙燕姿": ["华语流行"],
  "蔡依林": ["流行舞曲"],
  "杨丞琳": ["华语流行"],
  "萧亚轩": ["流行舞曲"],
  "张惠妹": ["华语流行"],
  "林忆莲": ["华语流行"],
  "莫文蔚": ["华语流行"],
  "梁静茹": ["华语流行"],
  "刘若英": ["华语流行"],
  "范玮琪": ["华语流行"],
  "张韶涵": ["华语流行"],
  "王心凌": ["华语流行"],
  "田馥甄": ["华语流行"],
  "杨宗纬": ["华语流行"],
  "萧敬腾": ["华语流行"],
  "林宥嘉": ["独立流行"],
  "吴青峰": ["独立流行"],
  "蔡健雅": ["华语流行"],
  "戴佩妮": ["华语流行"],
  "张震岳": ["嘻哈/说唱"],
  "MC HotDog": ["嘻哈/说唱"],
  "热狗": ["嘻哈/说唱"],
  "蛋堡": ["爵士嘻哈"],
  "国蛋": ["爵士嘻哈"],
  "顽童": ["嘻哈/说唱"],
  "瘦子": ["嘻哈/说唱"],
  "大渊": ["嘻哈/说唱"],
  "小春": ["嘻哈/说唱"],
  "唐溢": ["嘻哈/说唱"],
  "Tyga": ["嘻哈/说唱"],
  "法老": ["硬核说唱"],
  "杨和苏": ["硬核说唱"],
  "那吾克热": ["硬核说唱"],
  "艾热": ["嘻哈/说唱"],
  "王以太": ["流行说唱"],
  "刘聪": ["旋律说唱"],
  "功夫胖": ["嘻哈/说唱"],
  "盛宇": ["嘻哈/说唱"],
  "GAI周延": ["嘻哈/说唱"],
  "贝贝": ["硬核说唱"],
  "马思唯": ["嘻哈/说唱"],
  "KnowKnow": ["嘻哈/说唱"],
  "Melo": ["嘻哈/说唱"],
  "PSY.P": ["嘻哈/说唱"],
  "阿冗": ["华语流行"],
  "隔壁老樊": ["华语民谣"],
  "海来阿木": ["华语民谣"],
  "崔健": ["华语摇滚"],
  "窦唯": ["华语摇滚"],
  "黑豹乐队": ["华语摇滚"],
  "唐朝乐队": ["华语摇滚"],
  "Beyond": ["粤语流行", "摇滚"],
  "黄家驹": ["粤语流行", "摇滚"],
  "汪峰": ["华语摇滚"],
  "许巍": ["华语摇滚"],
  "郑钧": ["华语摇滚"],
  "朴树": ["独立流行"],
  "李志": ["独立民谣"],
  "万能青年旅店": ["独立摇滚"],
  "草东没有派对": ["独立摇滚"],
  "痛仰乐队": ["华语摇滚"],
  "新裤子": ["独立摇滚"],
  "刺猬": ["独立摇滚"],
  "逃跑计划": ["独立摇滚"],
  "落日飞车": ["独立摇滚"],
  "告五人": ["独立流行"],
  "茄子蛋": ["独立摇滚"],
  "八三夭": ["华语摇滚"],
  "信乐团": ["华语摇滚"],
  "闪灵": ["金属"],
  "丁世光": ["R&B"],
  "袁娅维": ["R&B"],
  "李玟": ["R&B", "流行舞曲"],
  "BTS": ["K-Pop"],
  "Bangtan": ["K-Pop"],
  "BLACKPINK": ["K-Pop"],
  "TWICE": ["K-Pop"],
  "EXO": ["K-Pop"],
  "NCT": ["K-Pop"],
  "Stray Kids": ["K-Pop"],
  "ATEEZ": ["K-Pop"],
  "SEVENTEEN": ["K-Pop"],
  "Red Velvet": ["K-Pop"],
  "MAMAMOO": ["K-Pop"],
  "ITZY": ["K-Pop"],
  "NewJeans": ["K-Pop"],
  "aespa": ["K-Pop"],
  "LE SSERAFIM": ["K-Pop"],
  "IVE": ["K-Pop"],
  "BIGBANG": ["K-Pop"],
  "少女时代": ["K-Pop"],
  "f(x)": ["K-Pop"],
  "2NE1": ["K-Pop"],
  "Super Junior": ["K-Pop"],
  "SHINee": ["K-Pop"],
  "东方神起": ["K-Pop"],
  "Apink": ["K-Pop"],
  "IU": ["K-Pop"],
  "太阳": ["K-Pop"],
  "权志龙": ["K-Pop"],
  "朴彩英": ["K-Pop"],
  "金泰妍": ["K-Pop"],
  "边伯贤": ["K-Pop"],
  "金钟大": ["K-Pop"],
  "米津玄师": ["J-Pop"],
  "Aimer": ["J-Pop"],
  "宇多田光": ["J-Pop"],
  "滨崎步": ["J-Pop"],
  "安室奈美惠": ["J-Pop"],
  "仓木麻衣": ["J-Pop"],
  "中岛美嘉": ["J-Pop"],
  "鬼束千寻": ["J-Pop"],
  "King Gnu": ["J-Pop", "摇滚"],
  "Official髭男dism": ["J-Pop"],
  "藤井风": ["J-Pop"],
  "ReoNa": ["J-Pop"],
  "ZUTOMAYO": ["J-Pop"],
  "EVe": ["J-Pop"],
  "凛冽时雨": ["J-Pop", "摇滚"],
  "POLYSICS": ["J-Pop", "摇滚"],
  "泽野弘之": ["二次元/ACG"],
  "梶浦由记": ["二次元/ACG"],
  "菅野洋子": ["二次元/ACG"],
  "久石让": ["古典", "轻音乐"],
  "坂本龙一": ["古典", "电子"],
  "Yoko Kanno": ["二次元/ACG"],
  "Hiroyuki Sawano": ["二次元/ACG"],
  "Yuki Kajiura": ["二次元/ACG"],
  "Taylor Swift": ["欧美流行"],
  "Adele": ["欧美流行"],
  "Ed Sheeran": ["欧美流行"],
  "Billie Eilish": ["欧美流行"],
  "Dua Lipa": ["流行舞曲"],
  "Lady Gaga": ["流行舞曲"],
  "Rihanna": ["R&B", "流行舞曲"],
  "Katy Perry": ["欧美流行"],
  "Justin Bieber": ["欧美流行"],
  "Ariana Grande": ["R&B", "欧美流行"],
  "Shawn Mendes": ["欧美流行"],
  "Harry Styles": ["欧美流行"],
  "Selena Gomez": ["欧美流行"],
  "Miley Cyrus": ["欧美流行"],
  "Lana Del Rey": ["独立流行"],
  "Post Malone": ["欧美流行"],
  "Charlie Puth": ["欧美流行"],
  "Madonna": ["流行舞曲"],
  "J. Cole": ["嘻哈/说唱"],
  "Travis Scott": ["陷阱说唱"],
  "Snoop Dogg": ["嘻哈/说唱"],
  "Dr. Dre": ["嘻哈/说唱"],
  "50 Cent": ["硬核说唱"],
  "Lil Wayne": ["嘻哈/说唱"],
  "Cardi B": ["嘻哈/说唱"],
  "Nicki Minaj": ["嘻哈/说唱"],
  "Megan Thee Stallion": ["嘻哈/说唱"],
  "21 Savage": ["陷阱说唱"],
  "Migos": ["陷阱说唱"],
  "Offset": ["陷阱说唱"],
  "Quavo": ["陷阱说唱"],
  "Juice WRLD": ["情绪说唱"],
  "XXXTentacion": ["情绪说唱"],
  "Lil Peep": ["情绪说唱"],
  "Lil Uzi Vert": ["情绪说唱"],
  "Playboi Carti": ["陷阱说唱"],
  "Future": ["陷阱说唱"],
  "Lil Baby": ["陷阱说唱"],
  "Gunna": ["陷阱说唱"],
  "Young Thug": ["陷阱说唱"],
  "Tyler the Creator": ["嘻哈/说唱"],
  "Mac Miller": ["爵士嘻哈"],
  "A$AP Rocky": ["嘻哈/说唱"],
  "Chance the Rapper": ["爵士嘻哈"],
  "Kanye West": ["嘻哈/说唱"],
  "Nirvana": ["摇滚"],
  "Metallica": ["金属"],
  "Linkin Park": ["摇滚"],
  "Radiohead": ["另类摇滚"],
  "Arctic Monkeys": ["独立摇滚"],
  "Green Day": ["朋克"],
  "Foo Fighters": ["摇滚"],
  "Red Hot Chili Peppers": ["摇滚"],
  "Muse": ["另类摇滚"],
  "Oasis": ["英伦摇滚"],
  "Blur": ["英伦摇滚"],
  "Pink Floyd": ["迷幻摇滚"],
  "Led Zeppelin": ["摇滚"],
  "The Rolling Stones": ["摇滚"],
  "AC/DC": ["摇滚"],
  "Guns N Roses": ["摇滚"],
  "System of a Down": ["金属"],
  "Slipknot": ["金属"],
  "Rammstein": ["金属"],
  "Imagine Dragons": ["流行摇滚"],
  "Twenty One Pilots": ["另类流行"],
  "Daft Punk": ["电子"],
  "Marshmello": ["电子舞曲"],
  "Calvin Harris": ["电子舞曲"],
  "Avicii": ["电子舞曲"],
  "David Guetta": ["电子舞曲"],
  "Martin Garrix": ["电子舞曲"],
  "Skrillex": ["回响贝斯"],
  "Deadmau5": ["电子"],
  "Zedd": ["电子舞曲"],
  "Kygo": ["电子"],
  "Flume": ["电子"],
  "Aphex Twin": ["电子"],
  "Boards of Canada": ["氛围音乐"],
  "Tiesto": ["电子舞曲"],
  "Armin van Buuren": ["迷幻舞曲"],
  "Above & Beyond": ["迷幻舞曲"],
  "Illenium": ["电子"],
  "Madeon": ["电子"],
  "Porter Robinson": ["电子"],
  "Virtual Riot": ["回响贝斯"],
  "Kaytranada": ["电子"],
  "Miles Davis": ["爵士"],
  "John Coltrane": ["爵士"],
  "Charlie Parker": ["爵士"],
  "Duke Ellington": ["爵士"],
  "Louis Armstrong": ["爵士"],
  "Billie Holiday": ["爵士"],
  "Ella Fitzgerald": ["爵士"],
  "Norah Jones": ["爵士"],
  "王若琳": ["爵士"],
  "Diana Krall": ["爵士"],
  "Robert Johnson": ["蓝调"],
  "Muddy Waters": ["蓝调"],
  "Buddy Guy": ["蓝调"],
  "John Lee Hooker": ["蓝调"],
  "Stevie Ray Vaughan": ["蓝调"],
  "Ludovico Einaudi": ["古典"],
  "Yiruma": ["钢琴曲"],
  "Max Richter": ["古典", "氛围音乐"],
  "Joep Beving": ["古典", "钢琴曲"],
  "Ólafur Arnalds": ["古典", "氛围音乐"],
  "Nils Frahm": ["古典", "电子"],
  "Hans Zimmer": ["交响乐"],
  "John Williams": ["交响乐"],
  "Ennio Morricone": ["交响乐"],
  "Bad Bunny": ["拉丁"],
  "J Balvin": ["拉丁"],
  "Shakira": ["拉丁流行"],
  "Enrique Iglesias": ["拉丁流行"],
  "Daddy Yankee": ["拉丁"],
  "Bob Marley": ["雷鬼"],
  "Peter Tosh": ["雷鬼"],
  "Jimmy Cliff": ["雷鬼"],
  "容祖儿": ["粤语流行"],
  "谢霆锋": ["粤语流行"],
  "杨千嬅": ["粤语流行"],
  "陈慧琳": ["粤语流行"],
  "郑秀文": ["粤语流行"],
  "古巨基": ["粤语流行"],
  "李克勤": ["粤语流行"],
  "许志安": ["粤语流行"],
  "张敬轩": ["粤语流行"],
  "王菀之": ["粤语流行"],
  "卫兰": ["粤语流行"],
  "麦浚龙": ["粤语流行"],
  "Dear Jane": ["粤语流行", "摇滚"],
  "Supper Moment": ["粤语流行", "摇滚"],
  "RubberBand": ["粤语流行", "摇滚"],
  "押尾光太郎": ["轻音乐"],
  "岸部真明": ["轻音乐"],
  "DEPAPEPE": ["轻音乐"],
  "Tycho": ["氛围音乐"],
  "Emancipator": ["氛围音乐", "电子"],
  "Bonobo": ["电子", "氛围音乐"]
,
  "夏之禹": ["嘻哈/说唱"],
  "小老虎": ["嘻哈/说唱"],
  "小青龙": ["嘻哈/说唱"],
  "龙胆紫": ["嘻哈/说唱"],
  "阴三儿": ["硬核说唱"],
  "Sbazzo": ["嘻哈/说唱"],
  "李小龙": ["嘻哈/说唱"],
  "C-Block": ["嘻哈/说唱"],
  "西奥": ["嘻哈/说唱"],
  "于意": ["嘻哈/说唱"],
  "Ranzer": ["嘻哈/说唱"],
  "陈峥嵘": ["嘻哈/说唱"],
  "辛巴": ["嘻哈/说唱"],
  "V.O.B": ["嘻哈/说唱"],
  "Cream D": ["硬核说唱"],
  "派克特": ["硬核说唱"],
  "老派": ["硬核说唱"],
  "鱼头": ["嘻哈/说唱"],
  "Kigga": ["嘻哈/说唱"],
  "Dirty Twinz": ["嘻哈/说唱"],
  "贰万": ["嘻哈/说唱"],
  "早安": ["嘻哈/说唱"],
  "ICE": ["流行说唱"],
  "李佳隆": ["旋律说唱"],
  "周汤豪": ["流行说唱"],
  "Dough-Boy": ["嘻哈/说唱"],
  "YoungQueenz": ["陷阱说唱"],
  "Tommy Grooves": ["R&B"],
  "EPIK HIGH": ["嘻哈/说唱"],
  "回春丹": ["独立摇滚"],
  "霓虹花园": ["独立摇滚"],
  "夏日入侵企画": ["独立摇滚"],
  "棱镜": ["独立流行"],
  "房东的猫": ["独立民谣"],
  "鹿先森乐队": ["独立民谣"],
  "陈鸿宇": ["独立民谣"],
  "谢春花": ["独立民谣"],
  "Jam": ["独立民谣"],
  "花粥": ["独立民谣"],
  "丢火车": ["独立摇滚"],
  "岛屿心情": ["独立摇滚"],
  "盘尼西林": ["独立摇滚"],
  "海龟先生": ["独立摇滚"],
  "五条人": ["独立民谣"],
  "九连真人": ["独立摇滚"],
  "寸铁": ["独立摇滚"],
  "腰乐队": ["独立摇滚"],
  "野外合作社": ["独立摇滚"],
  "声音碎片": ["独立摇滚"],
  "声音玩具": ["独立摇滚"],
  "木马": ["独立摇滚"],
  "重塑雕像的权利": ["独立摇滚"],
  "PK14": ["独立摇滚"],
  "Carsick Cars": ["独立摇滚"],
  "大波浪": ["电子", "独立摇滚"],
  "海皮威尔": ["独立摇滚"],
  "白纸扇": ["独立摇滚"],
  "法兹": ["独立摇滚"],
  "疯医": ["独立摇滚"],
  "张玮玮": ["独立民谣"],
  "郭龙": ["独立民谣"],
  "万晓利": ["独立民谣"],
  "周云蓬": ["独立民谣"],
  "野孩子": ["独立民谣"],
  "小河": ["独立民谣"],
  "美好药店": ["独立民谣"],
  "左小祖咒": ["独立摇滚"],
  "苏阳": ["世界音乐"],
  "杭盖乐队": ["世界音乐"],
  "魏如萱": ["独立流行"],
  "魏如昀": ["独立流行"],
  "焦安溥": ["独立流行"],
  "陈绮贞": ["独立流行"],
  "张悬": ["独立流行"],
  "陈珊妮": ["独立流行"],
  "脆乐团": ["独立流行"],
  "Vast & Hazy": ["独立流行"],
  "康士坦的变化球": ["独立摇滚"],
  "傻子与白痴": ["独立摇滚"],
  "老王乐队": ["独立摇滚"],
  "当代电影大师": ["独立摇滚"],
  "伤心欲绝": ["独立摇滚"],
  "法兰黛": ["独立流行"],
  "南瓜妮歌迷俱乐部": ["独立摇滚"],
  "先知玛莉": ["独立摇滚"],
  "BTS J-Hope": ["K-Pop"],
  "BTS RM": ["K-Pop"],
  "BTS SUGA": ["K-Pop"],
  "BTS Jungkook": ["K-Pop"],
  "BTS Jimin": ["K-Pop"],
  "BTS V": ["K-Pop"],
  "TXT": ["K-Pop"],
  "ENHYPEN": ["K-Pop"],
  "MONSTA X": ["K-Pop"],
  "GOT7": ["K-Pop"],
  "2PM": ["K-Pop"],
  "WINNER": ["K-Pop"],
  "iKON": ["K-Pop"],
  "TREASURE": ["K-Pop"],
  "ASTRO": ["K-Pop"],
  "SF9": ["K-Pop"],
  "Pentagon": ["K-Pop"],
  "The Boyz": ["K-Pop"],
  "Golden Child": ["K-Pop"],
  "WJSN": ["K-Pop"],
  "宇宙少女": ["K-Pop"],
  "Oh My Girl": ["K-Pop"],
  "fromis_9": ["K-Pop"],
  "IDLE": ["K-Pop"],
  "Dreamcatcher": ["K-Pop"],
  "Everglow": ["K-Pop"],
  "STAYC": ["K-Pop"],
  "NMIXX": ["K-Pop"],
  "KISS OF LIFE": ["K-Pop"],
  "BABYMONSTER": ["K-Pop"],
  "太妍": ["K-Pop"],
  "GDragon": ["K-Pop"],
  "CL": ["K-Pop"],
  "LeeHi": ["R&B", "K-Pop"],
  "DEAN": ["R&B", "K-Pop"],
  "Crush": ["R&B", "K-Pop"],
  "ZICO": ["嘻哈/说唱"],
  "BewhY": ["嘻哈/说唱"],
  "Sik-K": ["嘻哈/说唱"],
  "pH-1": ["嘻哈/说唱"],
  "Jay Park": ["R&B", "嘻哈/说唱"],
  "禹元材": ["嘻哈/说唱"],
  "Mrs. GREEN APPLE": ["J-Pop"],
  "back number": ["J-Pop"],
  "SUPER BEAVER": ["J-Pop"],
  "BUMP OF CHICKEN": ["J-Pop"],
  "Shishamo": ["J-Pop"],
  "WANIMA": ["J-Pop", "摇滚"],
  "androp": ["J-Pop"],
  "Alexandros": ["摇滚"],
  "MAN WITH A MISSION": ["摇滚"],
  "coldrain": ["摇滚", "金属"],
  "SiM": ["摇滚"],
  "Crystal Lake": ["金属"],
  "Crossfaith": ["金属"],
  "10-FEET": ["朋克"],
  "Ken Yokoyama": ["朋克"],
  "Hi-STANDARD": ["朋克"],
  "Perfume": ["J-Pop"],
  "Kyary Pamyu Pamyu": ["J-Pop"],
  "卡莉怪妞": ["J-Pop"],
  "香椎由宇": ["J-Pop"],
  "星期三的康帕内拉": ["J-Pop"],
  "开心少女组": ["J-Pop"],
  "BE:FIRST": ["J-Pop"],
  "Da-iCE": ["J-Pop"],
  "L'Arc~en~Ciel": ["摇滚"],
  "彩虹乐团": ["摇滚"],
  "X JAPAN": ["金属", "摇滚"],
  "GLAY": ["摇滚"],
  "LUNA SEA": ["摇滚"],
  "Dir en grey": ["金属"],
  "the GazettE": ["摇滚"],
  "Alice Nine": ["摇滚"],
  "Acid Black Cherry": ["摇滚"],
  "MY FIRST STORY": ["摇滚"],
  "Survive Said The Prophet": ["摇滚"],
  "Arcade Fire": ["独立摇滚"],
  "The National": ["独立摇滚"],
  "Bon Iver": ["独立民谣"],
  "Fleet Foxes": ["独立民谣"],
  "Vampire Weekend": ["独立摇滚"],
  "Tame Impala": ["迷幻摇滚"],
  "Mac DeMarco": ["独立摇滚"],
  "Beach House": ["独立摇滚"],
  "Phoebe Bridgers": ["独立民谣"],
  "Snail Mail": ["独立摇滚"],
  "Japanese Breakfast": ["独立摇滚"],
  "Big Thief": ["独立民谣"],
  "Sufjan Stevens": ["独立民谣"],
  "Father John Misty": ["独立民谣"],
  "Mitski": ["独立摇滚"],
  "Boygenius": ["独立摇滚"],
  "Hozier": ["独立民谣"],
  "Florence and the Machine": ["独立流行"],
  "The xx": ["独立流行"],
  "Alt-J": ["独立摇滚"],
  "Glass Animals": ["独立摇滚"],
  "MGMT": ["独立摇滚"],
  "Modest Mouse": ["独立摇滚"],
  "Death Cab for Cutie": ["独立摇滚"],
  "The Strokes": ["独立摇滚"],
  "Interpol": ["独立摇滚"],
  "The Killers": ["独立摇滚"],
  "Solange": ["R&B", "灵魂乐"],
  "H.E.R.": ["R&B"],
  "Jhené Aiko": ["R&B"],
  "Ari Lennox": ["R&B"],
  "Snoh Aalegra": ["R&B", "灵魂乐"],
  "Jill Scott": ["R&B", "灵魂乐"],
  "Maxwell": ["R&B", "灵魂乐"],
  "D'Angelo": ["R&B", "放克"],
  "Anderson .Paak": ["R&B", "放克"],
  "Thundercat": ["R&B", "放克"],
  "Kali Uchis": ["R&B"],
  "Steve Lacy": ["R&B"],
  "Omar Apollo": ["R&B"],
  "Giveon": ["R&B"],
  "Brent Faiyaz": ["R&B"],
  "Daniel Caesar": ["R&B", "灵魂乐"],
  "Leon Bridges": ["R&B", "灵魂乐"],
  "Four Tet": ["电子"],
  "Jon Hopkins": ["电子"],
  "Caribou": ["电子"],
  "Jamie xx": ["电子"],
  "Burial": ["氛围音乐"],
  "Floating Points": ["电子"],
  "DJ Shadow": ["电子"],
  "Autechre": ["电子"],
  "Squarepusher": ["电子"],
  "Oneohtrix Point Never": ["电子"],
  "Sophie": ["电子"],
  "Arca": ["电子"],
  "FKA twigs": ["电子", "R&B"],
  "James Blake": ["电子", "R&B"],
  "Mount Kimbie": ["电子"],
  "Swedish House Mafia": ["电子舞曲"],
  "Axwell": ["电子舞曲"],
  "Ingrosso": ["电子舞曲"],
  "Alesso": ["电子舞曲"],
  "SHM": ["电子舞曲"],
  "Hardwell": ["电子舞曲"],
  "Don Diablo": ["电子舞曲"],
  "Oliver Heldens": ["电子舞曲"],
  "Tchami": ["电子舞曲"],
  "Malaa": ["电子舞曲"],
  "DJ Snake": ["电子舞曲"],
  "Diplo": ["电子"],
  "Major Lazer": ["电子舞曲"],
  "Yellow Claw": ["电子舞曲"],
  "Knife Party": ["电子舞曲"],
  "Pegboard Nerds": ["电子舞曲"],
  "Rezz": ["电子"],
  "Subtronics": ["回响贝斯"],
  "Excision": ["回响贝斯"],
  "Demi Lovato": ["欧美流行"],
  "Camila Cabello": ["欧美流行"],
  "Halsey": ["欧美流行"],
  "Lizzo": ["欧美流行", "嘻哈/说唱"],
  "Doja Cat": ["欧美流行", "嘻哈/说唱"],
  "Chappell Roan": ["欧美流行"],
  "Olivia Rodrigo": ["欧美流行"],
  "Sabrina Carpenter": ["欧美流行"],
  "Tate McRae": ["欧美流行"],
  "Conan Gray": ["欧美流行"],
  "Troye Sivan": ["流行舞曲"],
  "Jason Derulo": ["流行舞曲"],
  "Carly Rae Jepsen": ["欧美流行"],
  "The Who": ["摇滚"],
  "The Kinks": ["摇滚"],
  "The Doors": ["摇滚"],
  "Jim Morrison": ["摇滚"],
  "Jimi Hendrix": ["摇滚"],
  "Janis Joplin": ["摇滚"],
  "David Bowie": ["迷幻摇滚"],
  "Freddie Mercury": ["摇滚"],
  "Elton John": ["欧美流行"],
  "Billy Joel": ["欧美流行"],
  "Bruce Springsteen": ["摇滚"],
  "Tom Petty": ["摇滚"],
  "Neil Young": ["民谣摇滚"],
  "Bob Dylan": ["民谣"],
  "Paul Simon": ["世界音乐", "民谣"],
  "Simon & Garfunkel": ["民谣"],
  "Herbie Hancock": ["爵士"],
  "Wayne Shorter": ["爵士"],
  "Thelonious Monk": ["爵士"],
  "Charles Mingus": ["爵士"],
  "Art Blakey": ["爵士"],
  "Sonny Rollins": ["爵士"],
  "Dizzy Gillespie": ["爵士"],
  "Count Basie": ["爵士"],
  "Wynton Marsalis": ["爵士"],
  "Kamasi Washington": ["爵士"],
  "Robert Glasper": ["爵士", "R&B"],
  "Esperanza Spalding": ["爵士"],
  "Debussy": ["古典"],
  "Chopin": ["古典"],
  "肖邦": ["古典"],
  "Beethoven": ["古典"],
  "贝多芬": ["古典"],
  "Mozart": ["古典"],
  "莫扎特": ["古典"],
  "Bach": ["古典"],
  "巴赫": ["古典"],
  "Tchaikovsky": ["古典"],
  "柴可夫斯基": ["古典"],
  "Vivaldi": ["古典"],
  "维瓦尔第": ["古典"],
  "Alexandre Desplat": ["交响乐"],
  "Howard Shore": ["交响乐"],
  "James Horner": ["交响乐"],
  "Jóhann Jóhannsson": ["氛围音乐", "古典"],
  "王建民": ["古风/中国风"],
  "赵季平": ["古风/中国风"],
  "谭盾": ["古典", "世界音乐"],
  "林海": ["轻音乐"],
  "何训田": ["世界音乐"],
  "林子祥": ["粤语流行"],
  "叶倩文": ["粤语流行"],
  "谭咏麟": ["粤语流行"],
  "张国荣": ["粤语流行"],
  "梅艳芳": ["粤语流行"],
  "关淑怡": ["粤语流行"],
  "王杰": ["华语流行"],
  "罗大佑": ["华语流行"],
  "李宗盛": ["华语流行"],
  "周华健": ["华语流行"],
  "任贤齐": ["华语流行"],
  "张宇": ["华语流行"],
  "伍佰": ["华语摇滚"],
  "张信哲": ["华语流行"],
  "庾澄庆": ["华语流行"],
  "童安格": ["华语流行"],
  "姜育恒": ["华语流行"],
  "费玉清": ["华语流行"],
  "双笙": ["古风/中国风"],
  "Winky诗": ["古风/中国风"],
  "伦桑": ["古风/中国风"],
  "排骨教主": ["古风/中国风"],
  "萧忆情": ["古风/中国风"],
  "西瓜jun": ["古风/中国风"],
  "哦漏": ["古风/中国风"],
  "不才": ["古风/中国风"],
  "以冬": ["古风/中国风"],
  "玄觞": ["古风/中国风"],
  "Assen捷": ["古风/中国风"],
  "陈鹏宇": ["古风/中国风"],
  "Lao干妈": ["古风/中国风"],
  "马友友": ["古典", "世界音乐"],
  "Yoyo Ma": ["古典", "世界音乐"],
  "邓丽君": ["华语流行"],
  "凤飞飞": ["华语流行"],
  "蔡琴": ["华语流行"],
  "Rosalía": ["拉丁"],
  "Karol G": ["拉丁"],
  "Anuel AA": ["拉丁"],
  "Rauw Alejandro": ["拉丁"],
  "Farruko": ["拉丁"],
  "Luis Fonsi": ["拉丁流行"],
  "Maluma": ["拉丁流行"],
  "Becky G": ["拉丁流行"],
  "Santana": ["拉丁摇滚"],
  "Sean Paul": ["雷鬼"],
  "Shaggy": ["雷鬼"],
  "Damian Marley": ["雷鬼"],
  "Ziggy Marley": ["雷鬼"],
  "Eric Clapton": ["蓝调", "摇滚"],
  "Gary Moore": ["蓝调", "摇滚"],
  "Albert King": ["蓝调"],
  "Freddie King": ["蓝调"],
  "Taj Mahal": ["蓝调"],
  "Keb Mo": ["蓝调"],
  "Boz Scaggs": ["蓝调"],
  "Joe Bonamassa": ["蓝调"],
  "Metro Boomin": ["陷阱说唱"],
  "Southside": ["陷阱说唱"],
  "Pi'erre Bourne": ["嘻哈/说唱"],
  "Wheezy": ["陷阱说唱"],
  "Mob": ["陷阱说唱"],
  "Chief Keef": ["陷阱说唱"],
  "A Boogie": ["旋律说唱"],
  "Polo G": ["旋律说唱"],
  "Lil Tjay": ["旋律说唱"],
  "Rod Wave": ["旋律说唱"],
  "Quando Rondo": ["旋律说唱"],
  "YoungBoy": ["陷阱说唱"],
  "NBA YoungBoy": ["陷阱说唱"],
  "NLE Choppa": ["陷阱说唱"],
  "Lil Durk": ["陷阱说唱"],
  "King Von": ["陷阱说唱"],
  "Pop Smoke": ["钻头说唱"],
  "Fivio Foreign": ["钻头说唱"],
  "Headie One": ["钻头说唱"],
  "Central Cee": ["流行说唱"],
  "Dave": ["嘻哈/说唱"],
  "Stormzy": ["嘻哈/说唱"],
  "J Hus": ["嘻哈/说唱"],
  "AJ Tracey": ["嘻哈/说唱"],
  "Slowthai": ["嘻哈/说唱"],
  "Little Simz": ["嘻哈/说唱"],
  "Denzel Curry": ["硬核说唱"],
  "JPEGMAFIA": ["实验说唱"],
  "Danny Brown": ["实验说唱"],
  "Earl Sweatshirt": ["抽象说唱"],
  "MIKE": ["抽象说唱"],
  "Andrea Bocelli": ["古典"],
  "Luciano Pavarotti": ["古典"],
  "帕瓦罗蒂": ["古典"],
  "Plácido Domingo": ["古典"],
  "多明戈": ["古典"],
  "王晰": ["华语流行"],
  "阿云嘎": ["华语流行"],
  "郑云龙": ["华语流行"],
  "蔡程昱": ["华语流行"],
  "滕格尔": ["世界音乐"],
  "龚琳娜": ["世界音乐", "古风/中国风"],
  "Lofi Girl": ["弛放"],
  "ChilledCow": ["弛放"],
  "Jinsang": ["弛放"],
  "Idealism": ["弛放"],
  "SwuM": ["弛放"],
  "barnes blvd": ["弛放"],
  "Kupla": ["弛放"],
  "Purrple Cat": ["弛放"],
  "E e": ["弛放"],
  "Saib": ["弛放"],
  "Flamingosis": ["放克"],
  "Johnny Cash": ["乡村"],
  "Dolly Parton": ["乡村"],
  "Willie Nelson": ["乡村"],
  "John Denver": ["乡村", "民谣"],
  "Kenny Rogers": ["乡村"],
  "Shania Twain": ["乡村"],
  "Carrie Underwood": ["乡村"],
  "Luke Combs": ["乡村"],
  "Morgan Wallen": ["乡村"],
  "Chris Stapleton": ["乡村", "蓝调"],
  "Zach Bryan": ["乡村", "民谣"],
  "Girls Generation": ["K-Pop"],
  "SNSD": ["K-Pop"],
  "TVXQ": ["K-Pop"],
  "Big Bang": ["K-Pop"],
  "Wonder Girls": ["K-Pop"],
  "miss A": ["K-Pop"],
  "4Minute": ["K-Pop"],
  "Beast": ["K-Pop"],
  "Highlight": ["K-Pop"],
  "Infinite": ["K-Pop"],
  "B1A4": ["K-Pop"],
  "Block B": ["嘻哈/说唱"],
  "Mino": ["嘻哈/说唱"],
  "BOBBY": ["嘻哈/说唱"],
  "宋闵浩": ["嘻哈/说唱"],
  "B.I": ["嘻哈/说唱"],
  "Mika Nakashima": ["J-Pop"],
  "Kokia": ["J-Pop"],
  "MISIA": ["J-Pop"],
  "生物股长": ["J-Pop"],
  "Ikimonogakari": ["J-Pop"],
  "猴子把戏": ["J-Pop", "摇滚"],
  "Superfly": ["摇滚", "J-Pop"],
  "Reol": ["J-Pop", "电子"],
  "许冠杰": ["粤语流行"],
  "罗文": ["粤语流行"],
  "甄妮": ["粤语流行"],
  "徐小凤": ["粤语流行"],
  "陈百强": ["粤语流行"],
  "林振强": ["粤语流行"],
  "黄霑": ["粤语流行"],
  "顾嘉辉": ["粤语流行"],
  "达明一派": ["粤语流行", "独立摇滚"],
  "黄耀明": ["粤语流行"],
  "刘以达": ["粤语流行"],
  "温拿乐队": ["粤语流行"],
  "Holly Herndon": ["电子"],
  "Laurel Halo": ["电子"],
  "Fatima Al Qadiri": ["电子"],
  "Kelela": ["电子", "R&B"],
  "Yves Tumor": ["电子", "独立摇滚"],
  "Shygirl": ["电子", "嘻哈/说唱"],
  "Coubo": ["电子", "弛放"]

};;

const CHINESE_RE = /[\u4e00-\u9fff]/;

function getLanguageGenre(artistName: string): string {
  const a = artistName || "";
  for (const [artist, genres] of Object.entries(ARTIST_GENRES)) {
    if (a.toLowerCase().includes(artist.toLowerCase())) return genres[0];
  }
  if (CHINESE_RE.test(a)) return "华语流行";
  if (/[\uac00-\ud7af]/.test(a)) return "K-Pop";
  if (/[\u3040-\u309f\u30a0-\u30ff]/.test(a)) return "J-Pop";
  if (/^[a-zA-Z]/.test(a)) return "欧美流行";
  return "未分类";
}

function getArtistGenres(artistName: string): string[] {
  const a = artistName || "";
  for (const [artist, genres] of Object.entries(ARTIST_GENRES)) {
    if (a.toLowerCase().includes(artist.toLowerCase())) return genres;
  }
  return [];
}

function scoreLyrics(lyrics: string): Record<string, number> {
  const scores: Record<string, number> = {};
  if (!lyrics) return scores;
  const lines = lyrics.toLowerCase().split("\n").filter((l: string) => l.trim() && !l.startsWith("["));
  const text = lines.join(" ");

  let rapScore = 0;
  for (const w of ["flow", "verse", "hook", "beat", "swag", "hustle", "yo", "flex", "drip", "lit",
    "说唱", "嘻哈", "押韵", "韵脚", "饶舌", "skr", "ayo", "trap", "dope", "gang"]) {
    if (text.includes(w)) rapScore += 2;
  }
  if (rapScore > 3) scores["嘻哈/说唱"] = Math.min(rapScore * 12, 75);

  let rockScore = 0;
  for (const w of ["吉他", "电吉他", "失真", "riff", "solo", "摇滚", "呐喊", "燃烧", "热血", "疯狂", "自由", "反抗", "愤怒", "怒吼"]) {
    if (text.includes(w)) rockScore += 2;
  }
  if (rockScore > 3) scores["摇滚"] = Math.min(rockScore * 10, 70);

  let folkScore = 0;
  for (const w of ["民谣", "木吉他", "故事", "远方", "流浪", "青春", "梦想", "田野", "故乡", "温柔", "acoustic", "folk", "弹唱"]) {
    if (text.includes(w)) folkScore += 2;
  }
  if (folkScore > 3) scores["民谣"] = Math.min(folkScore * 10, 65);

  let gfScore = 0;
  for (const w of ["古风", "红尘", "天涯", "江湖", "剑", "长安", "桃花", "烟雨", "琴", "笛", "箫", "琵琶", "古筝", "水墨", "轮回", "缘", "醉", "梦回", "青丝", "白发", "奈何", "彼岸", "浮生", "倾城", "萧瑟"]) {
    if (text.includes(w)) gfScore += 3;
  }
  if (gfScore > 3) scores["古风/中国风"] = Math.min(gfScore * 10, 85);

  let rnbScore = 0;
  for (const w of ["baby", "honey", "love you", "miss you", "want you", "need you", "温柔", "缠绵", "性感", "soul", "smooth"]) {
    if (text.includes(w)) rnbScore += 1;
  }
  if (rnbScore >= 4) scores["R&B"] = Math.min(rnbScore * 8, 50);

  let edmScore = 0;
  for (const w of ["dj", "remix", "电子", "电音", "drop", "bass", "club", "party", "跳舞", "蹦迪"]) {
    if (text.includes(w)) edmScore += 2;
  }
  if (edmScore > 3) scores["电子"] = Math.min(edmScore * 10, 60);

  return scores;
}

function textClassify(name: string, artistName: string, albumName?: string, allArtists?: string[]): string | null {
  const title = [name, albumName].filter(Boolean).join(" ").toLowerCase();
  if (/^[\u4e00-\u9fff]{0,5}纯音乐/.test(name) || title.includes("instrumental") || title.includes("钢琴曲")) {
    return "轻音乐";
  }
  const checks: [string, RegExp[]][] = [
    ["嘻哈/说唱", [/说唱/, /嘻哈/, /\brap\b/, /\btrap\b/, /\bfreestyle\b/, /\bdiss\b/, /饶舌/]],
    ["摇滚", [/摇滚/, /\brock\b/, /\bpunk\b/, /\bmetal\b/, /\b乐队\b/, /\b乐团\b/]],
    ["电子", [/电子/, /电音/, /\bedm\b/, /\bremix\b/, /\btechno\b/, /\bdubstep\b/]],
    ["民谣", [/民谣/, /\bfolk\b/, /弹唱/]],
    ["古风/中国风", [/古风/, /中国风/, /国风/, /戏腔/, /剑/, /侠/, /仙/, /赋/, /吟/, /墨/, /弦/, /阙/, /潇湘/, /萧瑟/, /断肠/, /天涯/, /红尘/, /缘/, /劫/, /醉/, /梦回/, /青丝/, /白发/, /桃花/, /长安/, /琵琶/, /笛/, /箫/, /拂/, /葬/, /君/, /卿/]],
    ["二次元/ACG", [/\bacg\b/, /vocaloid/, /初音/, /洛天依/]],
    ["R&B", [/r&b/, /\brnb\b/, /节奏布鲁斯/]],
    ["爵士", [/爵士/, /\bjazz\b/, /bossa/]],
    ["古典", [/古典/, /\bclassical\b/, /钢琴曲/, /\bsymphony\b/, /交响/, /协奏/]],
  ];
  const allText = [title, artistName, ...(allArtists || [])].filter(Boolean).join(" ").toLowerCase();
  for (const [genre, patterns] of checks) {
    for (const p of patterns) {
      if (p.test(title)) return genre;
      if (p.test(allText)) return genre;
    }
  }
  return null;
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get("id");
  if (!id) return NextResponse.json({ error: "Missing playlist id" }, { status: 400 });

  try {
    const { playlist_detail, lyric, song_wiki_summary } = await import("netease-cloud-music-api-alger");
    const result = await playlist_detail({ id: Number(id), cookie: "" });
    const data: any = result.body || result;
    const pl: any = data.playlist || data;

    if (pl?.tracks?.length > 0) {
      const tracks = pl.tracks;

      // Step 2: Batch-fetch wiki styles for ALL tracks
      const wikiMap: Record<number, string[]> = {};
      const batchSize = 5;
      for (let i = 0; i < tracks.length; i += batchSize) {
        const batch = tracks.slice(i, i + batchSize);
        await Promise.all(batch.map(async (track: any) => {
          try {
            const wr = await song_wiki_summary({ id: track.id, cookie: "" });
            const wd: any = wr.body || wr;
            const blocks = wd.data?.blocks || [];
            for (const block of blocks) {
              for (const c of block.creatives || []) {
                if (c.creativeType === "songTag") {
                  for (const res of c.resources || []) {
                    if (res.resourceType === "melody_style") {
                      const wikiStyle = res.uiElement?.mainTitle?.title;
                      const mapped = mapWikiStyle(wikiStyle);
                      if (mapped) {
                        if (!wikiMap[track.id]) wikiMap[track.id] = [];
                        if (!wikiMap[track.id].includes(mapped)) wikiMap[track.id].push(mapped);
                      }
                    }
                  }
                }
              }
            }
          } catch {}
        }));
        if (i + batchSize < tracks.length) await new Promise(r => setTimeout(r, 150));
      }

      // Step 3: Classify using multi-layer approach
      for (let i = 0; i < tracks.length; i += batchSize) {
        const batch = tracks.slice(i, i + batchSize);
        await Promise.all(batch.map(async (track: any) => {
          const artistName = track.ar?.[0]?.name || "";
          const allArtistNames = (track.ar || []).map((a: any) => a.name).filter(Boolean);
          const albumName = track.al?.name || "";

          // Level 1: Wiki style + artist refinement
          if (wikiMap[track.id] && wikiMap[track.id].length > 0) {
            let genres = [...wikiMap[track.id]];
            const artistGenres = getArtistGenres(artistName);
            for (const g of artistGenres) {
              if (!genres.includes(g)) genres.push(g);
            }
            (track as any)._genres = [...new Set(genres)];
            (track as any)._genre = genres[0];
            (track as any)._genreSource = "netease_wiki";
            (track as any)._confidence = 0.85;
            return;
          }

          // Level 2: Check artist database first
          const artistGenres = getArtistGenres(artistName);
          if (artistGenres.length > 0) {
            (track as any)._genres = [...new Set(artistGenres)];
            (track as any)._genre = artistGenres[0];
            (track as any)._genreSource = "artist";
            (track as any)._confidence = 0.6;
            return;
          }

          // Level 3: Lyrics analysis
          try {
            const lr = await lyric({ id: track.id, cookie: "" });
            const lb: any = lr.body || lr;
            const lyricText = lb.lrc?.lyric || "";
            const lyricScores = scoreLyrics(lyricText);
            let bestGenre = "";
            let bestScore = 0;
            for (const [g, s] of Object.entries(lyricScores)) {
              if (s > bestScore) { bestGenre = g; bestScore = s; }
            }
            if (bestGenre && bestScore >= 25) {
              (track as any)._genre = bestGenre;
              (track as any)._genres = [...new Set([bestGenre])];
              (track as any)._genreSource = "lyrics";
              (track as any)._confidence = Math.min(0.8, bestScore / 80);
              return;
            }
          } catch {}

          // Level 4: Text-based keyword matching
          const textGenre = textClassify(track.name, artistName, albumName, allArtistNames);
          if (textGenre) {
            (track as any)._genre = textGenre;
            (track as any)._genres = [...new Set([textGenre])];
            (track as any)._genreSource = "text";
            (track as any)._confidence = 0.5;
            return;
          }

          // Level 5: Language-based default
          (track as any)._genre = getLanguageGenre(artistName);
          (track as any)._genres = [...new Set([(track as any)._genre])];
          (track as any)._genreSource = "language";
          (track as any)._confidence = 0.25;
        }));
        if (i + batchSize < tracks.length) await new Promise(r => setTimeout(r, 150));
      }
    }
    return NextResponse.json(data);
  } catch (error: any) {
    return NextResponse.json(
      { error: error?.message || "Failed: " + String(error) },
      { status: 500 }
    );
  }
}